/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

import (
	"time"
)

// ScheduleJobDto struct for ScheduleJobDto
type ScheduleJobDto struct {
	// The id of the schedule job.
	Id string `json:"id,omitempty"`
	// The new status.
	Status string `json:"status,omitempty"`
	// The target date and time when the content should be scheduled.
	DueTime time.Time `json:"dueTime,omitempty"`
	// The color of the scheduled status.
	Color string `json:"color,omitempty"`
	// The user who schedule the content.
	ScheduledBy string `json:"scheduledBy"`
}
