/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// TemplatesDtoAllOf struct for TemplatesDtoAllOf
type TemplatesDtoAllOf struct {
	// The event consumers.
	Items []TemplateDto `json:"items,omitempty"`
}

// NewTemplatesDtoAllOf instantiates a new TemplatesDtoAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplatesDtoAllOf() *TemplatesDtoAllOf {
	this := TemplatesDtoAllOf{}
	return &this
}

// NewTemplatesDtoAllOfWithDefaults instantiates a new TemplatesDtoAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplatesDtoAllOfWithDefaults() *TemplatesDtoAllOf {
	this := TemplatesDtoAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *TemplatesDtoAllOf) GetItems() []TemplateDto {
	if o == nil || isNil(o.Items) {
		var ret []TemplateDto
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplatesDtoAllOf) GetItemsOk() ([]TemplateDto, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *TemplatesDtoAllOf) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TemplateDto and assigns it to the Items field.
func (o *TemplatesDtoAllOf) SetItems(v []TemplateDto) {
	o.Items = v
}

func (o TemplatesDtoAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableTemplatesDtoAllOf struct {
	value *TemplatesDtoAllOf
	isSet bool
}

func (v NullableTemplatesDtoAllOf) Get() *TemplatesDtoAllOf {
	return v.value
}

func (v *NullableTemplatesDtoAllOf) Set(val *TemplatesDtoAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplatesDtoAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplatesDtoAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplatesDtoAllOf(val *TemplatesDtoAllOf) *NullableTemplatesDtoAllOf {
	return &NullableTemplatesDtoAllOf{value: val, isSet: true}
}

func (v NullableTemplatesDtoAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplatesDtoAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


