/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// UpsertCommentDto struct for UpsertCommentDto
type UpsertCommentDto struct {
	// The comment text.
	Text string `json:"text"`
	// The url where the comment is created.
	Url NullableString `json:"url,omitempty"`
}

// NewUpsertCommentDto instantiates a new UpsertCommentDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpsertCommentDto(text string) *UpsertCommentDto {
	this := UpsertCommentDto{}
	this.Text = text
	return &this
}

// NewUpsertCommentDtoWithDefaults instantiates a new UpsertCommentDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpsertCommentDtoWithDefaults() *UpsertCommentDto {
	this := UpsertCommentDto{}
	return &this
}

// GetText returns the Text field value
func (o *UpsertCommentDto) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *UpsertCommentDto) GetTextOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *UpsertCommentDto) SetText(v string) {
	o.Text = v
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpsertCommentDto) GetUrl() string {
	if o == nil || isNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpsertCommentDto) GetUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *UpsertCommentDto) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *UpsertCommentDto) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *UpsertCommentDto) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *UpsertCommentDto) UnsetUrl() {
	o.Url.Unset()
}

func (o UpsertCommentDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["text"] = o.Text
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableUpsertCommentDto struct {
	value *UpsertCommentDto
	isSet bool
}

func (v NullableUpsertCommentDto) Get() *UpsertCommentDto {
	return v.value
}

func (v *NullableUpsertCommentDto) Set(val *UpsertCommentDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpsertCommentDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpsertCommentDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpsertCommentDto(val *UpsertCommentDto) *NullableUpsertCommentDto {
	return &NullableUpsertCommentDto{value: val, isSet: true}
}

func (v NullableUpsertCommentDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpsertCommentDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


