/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// ContributorsMetadata struct for ContributorsMetadata
type ContributorsMetadata struct {
	// Indicates whether the user has been invited.
	IsInvited string `json:"isInvited,omitempty"`
}
