/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// CallsUsagePerDateDto struct for CallsUsagePerDateDto
type CallsUsagePerDateDto struct {
	// The date when the usage was tracked.
	Date string `json:"date,omitempty"`
	// The total number of API calls.
	TotalCalls int64 `json:"totalCalls,omitempty"`
	// The total number of bytes transferred.
	TotalBytes int64 `json:"totalBytes,omitempty"`
	// The average duration in milliseconds.
	AverageElapsedMs float64 `json:"averageElapsedMs,omitempty"`
}
