/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// UiSettingsDto struct for UiSettingsDto
type UiSettingsDto struct {
	// True when the user can create apps.
	CanCreateApps bool `json:"canCreateApps,omitempty"`
}
