/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// SignalRRuleActionDto struct for SignalRRuleActionDto
type SignalRRuleActionDto struct {
	ActionType *string `json:"actionType"`
	// The connection string to the Azure SignalR.
	ConnectionString string `json:"connectionString"`
	// The name of the hub.
	HubName string         `json:"hubName"`
	Action  ActionTypeEnum `json:"action"`
	// Set the Name of the hub method received by the customer.
	MethodName *string `json:"methodName,omitempty"`
	// Define target users or groups by id or name. One item per line. Not needed for Broadcast action.
	Target *string `json:"target,omitempty"`
	// Leave it empty to use the full event as body.
	Payload *string `json:"payload,omitempty"`
}
