/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// RuleEventsDto struct for RuleEventsDto
type RuleEventsDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The rule events.
	Items []RuleEventDto `json:"items"`
	// The total number of rule events.
	Total *int64 `json:"total,omitempty"`
}

// NewRuleEventsDto instantiates a new RuleEventsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleEventsDto(links map[string]ResourceLink, items []RuleEventDto) *RuleEventsDto {
	this := RuleEventsDto{}
	this.Links = links
	this.Items = items
	return &this
}

// NewRuleEventsDtoWithDefaults instantiates a new RuleEventsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleEventsDtoWithDefaults() *RuleEventsDto {
	this := RuleEventsDto{}
	return &this
}

// GetLinks returns the Links field value
func (o *RuleEventsDto) GetLinks() map[string]ResourceLink {
	if o == nil {
		var ret map[string]ResourceLink
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *RuleEventsDto) GetLinksOk() (*map[string]ResourceLink, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *RuleEventsDto) SetLinks(v map[string]ResourceLink) {
	o.Links = v
}

// GetItems returns the Items field value
func (o *RuleEventsDto) GetItems() []RuleEventDto {
	if o == nil {
		var ret []RuleEventDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RuleEventsDto) GetItemsOk() ([]RuleEventDto, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RuleEventsDto) SetItems(v []RuleEventDto) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *RuleEventsDto) GetTotal() int64 {
	if o == nil || isNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RuleEventsDto) GetTotalOk() (*int64, bool) {
	if o == nil || isNil(o.Total) {
    return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *RuleEventsDto) HasTotal() bool {
	if o != nil && !isNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *RuleEventsDto) SetTotal(v int64) {
	o.Total = &v
}

func (o RuleEventsDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["_links"] = o.Links
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if !isNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableRuleEventsDto struct {
	value *RuleEventsDto
	isSet bool
}

func (v NullableRuleEventsDto) Get() *RuleEventsDto {
	return v.value
}

func (v *NullableRuleEventsDto) Set(val *RuleEventsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleEventsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleEventsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleEventsDto(val *RuleEventsDto) *NullableRuleEventsDto {
	return &NullableRuleEventsDto{value: val, isSet: true}
}

func (v NullableRuleEventsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleEventsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


