/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// ConfigureUiFieldsDto struct for ConfigureUiFieldsDto
type ConfigureUiFieldsDto struct {
	// The name of fields that are used in content lists.
	FieldsInLists *[]string `json:"fieldsInLists,omitempty"`
	// The name of fields that are used in content references.
	FieldsInReferences *[]string `json:"fieldsInReferences,omitempty"`
}
