/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// TranslateDto struct for TranslateDto
type TranslateDto struct {
	// The text to translate.
	Text string `json:"text"`
	// The target language.
	TargetLanguage string `json:"targetLanguage"`
	// The optional source language.
	SourceLanguage string `json:"sourceLanguage,omitempty"`
}
