/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// SchemaScriptsDto struct for SchemaScriptsDto
type SchemaScriptsDto struct {
	// The script that is executed for each query when querying contents.
	Query *string `json:"query,omitempty"`
	// The script that is executed when creating a content.
	Create *string `json:"create,omitempty"`
	// The script that is executed when updating a content.
	Update *string `json:"update,omitempty"`
	// The script that is executed when deleting a content.
	Delete *string `json:"delete,omitempty"`
	// The script that is executed when change a content status.
	Change *string `json:"change,omitempty"`
}
