/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// ReferencesFieldEditor the model 'ReferencesFieldEditor'
type ReferencesFieldEditor string

// List of ReferencesFieldEditor
const (
	ReferencesFieldEditorLIST       ReferencesFieldEditor = "List"
	ReferencesFieldEditorDROPDOWN   ReferencesFieldEditor = "Dropdown"
	ReferencesFieldEditorTAGS       ReferencesFieldEditor = "Tags"
	ReferencesFieldEditorCHECKBOXES ReferencesFieldEditor = "Checkboxes"
	ReferencesFieldEditorINPUT      ReferencesFieldEditor = "Input"
)
