/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// UiFieldPropertiesDtoAllOf struct for UiFieldPropertiesDtoAllOf
type UiFieldPropertiesDtoAllOf struct {
	// The editor that is used to manage this field.
	Editor OneOfUiFieldEditor `json:"editor,omitempty"`
}
