/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// BulkUpdateContentType the model 'BulkUpdateContentType'
type BulkUpdateContentType string

// List of BulkUpdateContentType
const (
	UPSERT        BulkUpdateContentType = "Upsert"
	CHANGE_STATUS BulkUpdateContentType = "ChangeStatus"
	CREATE        BulkUpdateContentType = "Create"
	DELETE        BulkUpdateContentType = "Delete"
	PATCH         BulkUpdateContentType = "Patch"
	UPDATE        BulkUpdateContentType = "Update"
	VALIDATE      BulkUpdateContentType = "Validate"
)
