/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// UpdatePatternDto struct for UpdatePatternDto
type UpdatePatternDto struct {
	// The name of the suggestion.
	Name string `json:"name"`
	// The regex pattern.
	Pattern string `json:"pattern"`
	// The regex message.
	Message *string `json:"message,omitempty"`
}
