/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// AppLanguagesDtoAllOf struct for AppLanguagesDtoAllOf
type AppLanguagesDtoAllOf struct {
	// The languages.
	Items []AppLanguageDto `json:"items"`
}
