/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

import (
	"os"
)

// InlineObject struct for InlineObject
type InlineObject struct {
	File **os.File `json:"File,omitempty"`
}
