/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// LogDownloadDto struct for LogDownloadDto
type LogDownloadDto struct {
	// The url to download the log.
	DownloadUrl *string `json:"downloadUrl,omitempty"`
}
