/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// JsonValueType the model 'JsonValueType'
type JsonValueType string

// List of JsonValueType
const (
	JsonValueTypeARRAY   JsonValueType = "Array"
	JsonValueTypeBOOLEAN JsonValueType = "Boolean"
	JsonValueTypeNULL    JsonValueType = "Null"
	JsonValueTypeNUMBER  JsonValueType = "Number"
	JsonValueTypeOBJECT  JsonValueType = "Object"
	JsonValueTypeSTRING  JsonValueType = "String"
)
