/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// SimulatedRuleEventDto struct for SimulatedRuleEventDto
type SimulatedRuleEventDto struct {
	// The unique event id.
	EventId string `json:"eventId"`
	// The name of the event.
	EventName string `json:"eventName"`
	// The source event.
	Event interface{} `json:"event"`
	// The enriched event.
	EnrichedEvent *interface{} `json:"enrichedEvent,omitempty"`
	// The data for the action.
	ActionName *string `json:"actionName,omitempty"`
	// The name of the action.
	ActionData *string `json:"actionData,omitempty"`
	// The name of the event.
	Error *string `json:"error,omitempty"`
	// The reason why the event has been skipped.
	SkipReasons []SkipReason `json:"skipReasons"`
}
