/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// FeatureDto struct for FeatureDto
type FeatureDto struct {
	// The name of the feature.
	Name string `json:"name"`
	// The description text.
	Text string `json:"text"`
}
