/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// FieldRuleDto struct for FieldRuleDto
type FieldRuleDto struct {
	Action FieldRuleAction `json:"action"`
	// The field to update.
	Field string `json:"field"`
	// The condition.
	Condition *string `json:"condition,omitempty"`
}
