/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// ImageFormat the model 'ImageFormat'
type ImageFormat string

// List of ImageFormat
const (
	AUTO ImageFormat = "Auto"
	PNG ImageFormat = "PNG"
	JPEG ImageFormat = "JPEG"
	TGA ImageFormat = "TGA"
	GIF ImageFormat = "GIF"
)
