/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

import (
	"time"
)

// DateTimeFieldPropertiesDtoAllOf struct for DateTimeFieldPropertiesDtoAllOf
type DateTimeFieldPropertiesDtoAllOf struct {
	// The default value for the field value.
	DefaultValue *time.Time `json:"defaultValue,omitempty"`
	// The maximum allowed value for the field value.
	MaxValue *time.Time `json:"maxValue,omitempty"`
	// The minimum allowed value for the field value.
	MinValue *time.Time `json:"minValue,omitempty"`
	// The editor that is used to manage this field.

}
