/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// FieldDtoAllOf struct for FieldDtoAllOf
type FieldDtoAllOf struct {
	// The id of the field.
	FieldId *int64 `json:"fieldId,omitempty"`
	// The name of the field. Must be unique within the schema.
	Name string `json:"name"`
	// Defines if the field is hidden.
	IsHidden *bool `json:"isHidden,omitempty"`
	// Defines if the field is locked.
	IsLocked *bool `json:"isLocked,omitempty"`
	// Defines if the field is disabled.
	IsDisabled *bool `json:"isDisabled,omitempty"`
	// Defines the partitioning of the field.
	Partitioning string `json:"partitioning"`
	Properties FieldPropertiesDto `json:"properties"`
	// The nested fields.
	Nested []NestedFieldDto `json:"nested,omitempty"`
}

// NewFieldDtoAllOf instantiates a new FieldDtoAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldDtoAllOf(name string, partitioning string, properties FieldPropertiesDto) *FieldDtoAllOf {
	this := FieldDtoAllOf{}
	this.Name = name
	this.Partitioning = partitioning
	this.Properties = properties
	return &this
}

// NewFieldDtoAllOfWithDefaults instantiates a new FieldDtoAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldDtoAllOfWithDefaults() *FieldDtoAllOf {
	this := FieldDtoAllOf{}
	return &this
}

// GetFieldId returns the FieldId field value if set, zero value otherwise.
func (o *FieldDtoAllOf) GetFieldId() int64 {
	if o == nil || isNil(o.FieldId) {
		var ret int64
		return ret
	}
	return *o.FieldId
}

// GetFieldIdOk returns a tuple with the FieldId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetFieldIdOk() (*int64, bool) {
	if o == nil || isNil(o.FieldId) {
    return nil, false
	}
	return o.FieldId, true
}

// HasFieldId returns a boolean if a field has been set.
func (o *FieldDtoAllOf) HasFieldId() bool {
	if o != nil && !isNil(o.FieldId) {
		return true
	}

	return false
}

// SetFieldId gets a reference to the given int64 and assigns it to the FieldId field.
func (o *FieldDtoAllOf) SetFieldId(v int64) {
	o.FieldId = &v
}

// GetName returns the Name field value
func (o *FieldDtoAllOf) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FieldDtoAllOf) SetName(v string) {
	o.Name = v
}

// GetIsHidden returns the IsHidden field value if set, zero value otherwise.
func (o *FieldDtoAllOf) GetIsHidden() bool {
	if o == nil || isNil(o.IsHidden) {
		var ret bool
		return ret
	}
	return *o.IsHidden
}

// GetIsHiddenOk returns a tuple with the IsHidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetIsHiddenOk() (*bool, bool) {
	if o == nil || isNil(o.IsHidden) {
    return nil, false
	}
	return o.IsHidden, true
}

// HasIsHidden returns a boolean if a field has been set.
func (o *FieldDtoAllOf) HasIsHidden() bool {
	if o != nil && !isNil(o.IsHidden) {
		return true
	}

	return false
}

// SetIsHidden gets a reference to the given bool and assigns it to the IsHidden field.
func (o *FieldDtoAllOf) SetIsHidden(v bool) {
	o.IsHidden = &v
}

// GetIsLocked returns the IsLocked field value if set, zero value otherwise.
func (o *FieldDtoAllOf) GetIsLocked() bool {
	if o == nil || isNil(o.IsLocked) {
		var ret bool
		return ret
	}
	return *o.IsLocked
}

// GetIsLockedOk returns a tuple with the IsLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetIsLockedOk() (*bool, bool) {
	if o == nil || isNil(o.IsLocked) {
    return nil, false
	}
	return o.IsLocked, true
}

// HasIsLocked returns a boolean if a field has been set.
func (o *FieldDtoAllOf) HasIsLocked() bool {
	if o != nil && !isNil(o.IsLocked) {
		return true
	}

	return false
}

// SetIsLocked gets a reference to the given bool and assigns it to the IsLocked field.
func (o *FieldDtoAllOf) SetIsLocked(v bool) {
	o.IsLocked = &v
}

// GetIsDisabled returns the IsDisabled field value if set, zero value otherwise.
func (o *FieldDtoAllOf) GetIsDisabled() bool {
	if o == nil || isNil(o.IsDisabled) {
		var ret bool
		return ret
	}
	return *o.IsDisabled
}

// GetIsDisabledOk returns a tuple with the IsDisabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetIsDisabledOk() (*bool, bool) {
	if o == nil || isNil(o.IsDisabled) {
    return nil, false
	}
	return o.IsDisabled, true
}

// HasIsDisabled returns a boolean if a field has been set.
func (o *FieldDtoAllOf) HasIsDisabled() bool {
	if o != nil && !isNil(o.IsDisabled) {
		return true
	}

	return false
}

// SetIsDisabled gets a reference to the given bool and assigns it to the IsDisabled field.
func (o *FieldDtoAllOf) SetIsDisabled(v bool) {
	o.IsDisabled = &v
}

// GetPartitioning returns the Partitioning field value
func (o *FieldDtoAllOf) GetPartitioning() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Partitioning
}

// GetPartitioningOk returns a tuple with the Partitioning field value
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetPartitioningOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Partitioning, true
}

// SetPartitioning sets field value
func (o *FieldDtoAllOf) SetPartitioning(v string) {
	o.Partitioning = v
}

// GetProperties returns the Properties field value
func (o *FieldDtoAllOf) GetProperties() FieldPropertiesDto {
	if o == nil {
		var ret FieldPropertiesDto
		return ret
	}

	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value
// and a boolean to check if the value has been set.
func (o *FieldDtoAllOf) GetPropertiesOk() (*FieldPropertiesDto, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Properties, true
}

// SetProperties sets field value
func (o *FieldDtoAllOf) SetProperties(v FieldPropertiesDto) {
	o.Properties = v
}

// GetNested returns the Nested field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FieldDtoAllOf) GetNested() []NestedFieldDto {
	if o == nil {
		var ret []NestedFieldDto
		return ret
	}
	return o.Nested
}

// GetNestedOk returns a tuple with the Nested field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FieldDtoAllOf) GetNestedOk() ([]NestedFieldDto, bool) {
	if o == nil || isNil(o.Nested) {
    return nil, false
	}
	return o.Nested, true
}

// HasNested returns a boolean if a field has been set.
func (o *FieldDtoAllOf) HasNested() bool {
	if o != nil && isNil(o.Nested) {
		return true
	}

	return false
}

// SetNested gets a reference to the given []NestedFieldDto and assigns it to the Nested field.
func (o *FieldDtoAllOf) SetNested(v []NestedFieldDto) {
	o.Nested = v
}

func (o FieldDtoAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.FieldId) {
		toSerialize["fieldId"] = o.FieldId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.IsHidden) {
		toSerialize["isHidden"] = o.IsHidden
	}
	if !isNil(o.IsLocked) {
		toSerialize["isLocked"] = o.IsLocked
	}
	if !isNil(o.IsDisabled) {
		toSerialize["isDisabled"] = o.IsDisabled
	}
	if true {
		toSerialize["partitioning"] = o.Partitioning
	}
	if true {
		toSerialize["properties"] = o.Properties
	}
	if o.Nested != nil {
		toSerialize["nested"] = o.Nested
	}
	return json.Marshal(toSerialize)
}

type NullableFieldDtoAllOf struct {
	value *FieldDtoAllOf
	isSet bool
}

func (v NullableFieldDtoAllOf) Get() *FieldDtoAllOf {
	return v.value
}

func (v *NullableFieldDtoAllOf) Set(val *FieldDtoAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldDtoAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldDtoAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldDtoAllOf(val *FieldDtoAllOf) *NullableFieldDtoAllOf {
	return &NullableFieldDtoAllOf{value: val, isSet: true}
}

func (v NullableFieldDtoAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldDtoAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


