/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// PatternDtoAllOf struct for PatternDtoAllOf
type PatternDtoAllOf struct {
	// Unique id of the pattern.
	Id string `json:"id,omitempty"`
	// The name of the suggestion.
	Name string `json:"name"`
	// The regex pattern.
	Pattern string `json:"pattern"`
	// The regex message.
	Message *string `json:"message,omitempty"`
}
