/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkflowsDto struct for WorkflowsDto
type WorkflowsDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The workflow.
	Items []WorkflowDto `json:"items"`
	// The errros that should be fixed.
	Errors []string `json:"errors"`
}

// NewWorkflowsDto instantiates a new WorkflowsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsDto(links map[string]ResourceLink, items []WorkflowDto, errors []string) *WorkflowsDto {
	this := WorkflowsDto{}
	this.Links = links
	this.Items = items
	this.Errors = errors
	return &this
}

// NewWorkflowsDtoWithDefaults instantiates a new WorkflowsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsDtoWithDefaults() *WorkflowsDto {
	this := WorkflowsDto{}
	return &this
}

// GetLinks returns the Links field value
func (o *WorkflowsDto) GetLinks() map[string]ResourceLink {
	if o == nil {
		var ret map[string]ResourceLink
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *WorkflowsDto) GetLinksOk() (*map[string]ResourceLink, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *WorkflowsDto) SetLinks(v map[string]ResourceLink) {
	o.Links = v
}

// GetItems returns the Items field value
func (o *WorkflowsDto) GetItems() []WorkflowDto {
	if o == nil {
		var ret []WorkflowDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *WorkflowsDto) GetItemsOk() ([]WorkflowDto, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *WorkflowsDto) SetItems(v []WorkflowDto) {
	o.Items = v
}

// GetErrors returns the Errors field value
func (o *WorkflowsDto) GetErrors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *WorkflowsDto) GetErrorsOk() ([]string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *WorkflowsDto) SetErrors(v []string) {
	o.Errors = v
}

func (o WorkflowsDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["_links"] = o.Links
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowsDto struct {
	value *WorkflowsDto
	isSet bool
}

func (v NullableWorkflowsDto) Get() *WorkflowsDto {
	return v.value
}

func (v *NullableWorkflowsDto) Set(val *WorkflowsDto) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsDto) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsDto(val *WorkflowsDto) *NullableWorkflowsDto {
	return &NullableWorkflowsDto{value: val, isSet: true}
}

func (v NullableWorkflowsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


