/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ManualRuleTriggerDto struct for ManualRuleTriggerDto
type ManualRuleTriggerDto struct {
	RuleTriggerDto
}

// NewManualRuleTriggerDto instantiates a new ManualRuleTriggerDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManualRuleTriggerDto(triggerType string) *ManualRuleTriggerDto {
	this := ManualRuleTriggerDto{}
	this.TriggerType = triggerType
	return &this
}

// NewManualRuleTriggerDtoWithDefaults instantiates a new ManualRuleTriggerDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManualRuleTriggerDtoWithDefaults() *ManualRuleTriggerDto {
	this := ManualRuleTriggerDto{}
	return &this
}

func (o ManualRuleTriggerDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedRuleTriggerDto, errRuleTriggerDto := json.Marshal(o.RuleTriggerDto)
	if errRuleTriggerDto != nil {
		return []byte{}, errRuleTriggerDto
	}
	errRuleTriggerDto = json.Unmarshal([]byte(serializedRuleTriggerDto), &toSerialize)
	if errRuleTriggerDto != nil {
		return []byte{}, errRuleTriggerDto
	}
	return json.Marshal(toSerialize)
}

type NullableManualRuleTriggerDto struct {
	value *ManualRuleTriggerDto
	isSet bool
}

func (v NullableManualRuleTriggerDto) Get() *ManualRuleTriggerDto {
	return v.value
}

func (v *NullableManualRuleTriggerDto) Set(val *ManualRuleTriggerDto) {
	v.value = val
	v.isSet = true
}

func (v NullableManualRuleTriggerDto) IsSet() bool {
	return v.isSet
}

func (v *NullableManualRuleTriggerDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManualRuleTriggerDto(val *ManualRuleTriggerDto) *NullableManualRuleTriggerDto {
	return &NullableManualRuleTriggerDto{value: val, isSet: true}
}

func (v NullableManualRuleTriggerDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManualRuleTriggerDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


