/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// TagsFieldEditor the model 'TagsFieldEditor'
type TagsFieldEditor string

// List of TagsFieldEditor
const (
	CHECKBOXES TagsFieldEditor = "Checkboxes"
)
