/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// ConfigureUiFieldsDto struct for ConfigureUiFieldsDto
type ConfigureUiFieldsDto struct {
	FieldsInLists      []string `json:"fieldsInLists,omitempty"`
	FieldsInReferences []string `json:"fieldsInReferences,omitempty"`
}
