/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// TemplateDto struct for TemplateDto
type TemplateDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The name of the template.
	Name string `json:"name"`
	// The title of the template.
	Title string `json:"title"`
	// The description of the template.
	Description string `json:"description"`
	// True, if the template is a starter.
	IsStarter bool `json:"isStarter,omitempty"`
}
