/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// StringFieldEditor the model 'StringFieldEditor'
type StringFieldEditor string

// List of StringFieldEditor
const (
	INPUT StringFieldEditor = "Input"
	COLOR StringFieldEditor = "Color"
	MARKDOWN StringFieldEditor = "Markdown"
	DROPDOWN StringFieldEditor = "Dropdown"
	HTML StringFieldEditor = "Html"
	RADIO StringFieldEditor = "Radio"
	RICH_TEXT StringFieldEditor = "RichText"
	SLUG StringFieldEditor = "Slug"
	STOCK_PHOTO StringFieldEditor = "StockPhoto"
	TEXT_AREA StringFieldEditor = "TextArea"
)
