/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// EmailRuleActionDtoAllOf struct for EmailRuleActionDtoAllOf
type EmailRuleActionDtoAllOf struct {
	// The IP address or host to the SMTP server.
	ServerHost string `json:"serverHost"`
	// The port to the SMTP server.
	ServerPort int32 `json:"serverPort"`
	// Specify whether the SMPT client uses Secure Sockets Layer (SSL) to encrypt the connection.
	ServerUseSsl bool `json:"serverUseSsl"`
	// The password for the SMTP server.
	ServerPassword string `json:"serverPassword"`
	// The username for the SMTP server.
	ServerUsername string `json:"serverUsername"`
	// The email sending address.
	MessageFrom string `json:"messageFrom"`
	// The email message will be sent to.
	MessageTo string `json:"messageTo"`
	// The subject line for this email message.
	MessageSubject string `json:"messageSubject"`
	// The message body.
	MessageBody string `json:"messageBody"`
}
