/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// AssetFolderDto struct for AssetFolderDto
type AssetFolderDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The id of the asset.
	Id string `json:"id,omitempty"`
	// The id of the parent folder. Empty for files without parent.
	ParentId string `json:"parentId,omitempty"`
	// The folder name.
	FolderName string `json:"folderName"`
	// The version of the asset folder.
	Version int64 `json:"version,omitempty"`
}
