/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// ContentDataOfStringAllOf struct for ContentDataOfStringAllOf
type ContentDataOfStringAllOf struct {
	ValidValues []KeyValuePairOfStringAndContentFieldData `json:"ValidValues,omitempty"`
}
