/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// CreateAssetFolderDto struct for CreateAssetFolderDto
type CreateAssetFolderDto struct {
	// The name of the folder.
	FolderName string `json:"folderName"`
	// The id of the parent folder.
	ParentId *string `json:"parentId,omitempty"`
}

// NewCreateAssetFolderDto instantiates a new CreateAssetFolderDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAssetFolderDto(folderName string) *CreateAssetFolderDto {
	this := CreateAssetFolderDto{}
	this.FolderName = folderName
	return &this
}

// NewCreateAssetFolderDtoWithDefaults instantiates a new CreateAssetFolderDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAssetFolderDtoWithDefaults() *CreateAssetFolderDto {
	this := CreateAssetFolderDto{}
	return &this
}

// GetFolderName returns the FolderName field value
func (o *CreateAssetFolderDto) GetFolderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FolderName
}

// GetFolderNameOk returns a tuple with the FolderName field value
// and a boolean to check if the value has been set.
func (o *CreateAssetFolderDto) GetFolderNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.FolderName, true
}

// SetFolderName sets field value
func (o *CreateAssetFolderDto) SetFolderName(v string) {
	o.FolderName = v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CreateAssetFolderDto) GetParentId() string {
	if o == nil || isNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAssetFolderDto) GetParentIdOk() (*string, bool) {
	if o == nil || isNil(o.ParentId) {
    return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CreateAssetFolderDto) HasParentId() bool {
	if o != nil && !isNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *CreateAssetFolderDto) SetParentId(v string) {
	o.ParentId = &v
}

func (o CreateAssetFolderDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["folderName"] = o.FolderName
	}
	if !isNil(o.ParentId) {
		toSerialize["parentId"] = o.ParentId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAssetFolderDto struct {
	value *CreateAssetFolderDto
	isSet bool
}

func (v NullableCreateAssetFolderDto) Get() *CreateAssetFolderDto {
	return v.value
}

func (v *NullableCreateAssetFolderDto) Set(val *CreateAssetFolderDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAssetFolderDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAssetFolderDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAssetFolderDto(val *CreateAssetFolderDto) *NullableCreateAssetFolderDto {
	return &NullableCreateAssetFolderDto{value: val, isSet: true}
}

func (v NullableCreateAssetFolderDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAssetFolderDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


