/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// AssetFoldersDto struct for AssetFoldersDto
type AssetFoldersDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The total number of assets.
	Total *int64 `json:"total,omitempty"`
	// The assets folders.
	Items []AssetFolderDto `json:"items"`
	// The path to the current folder.
	Path []AssetFolderDto `json:"path"`
}

// NewAssetFoldersDto instantiates a new AssetFoldersDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetFoldersDto(links map[string]ResourceLink, items []AssetFolderDto, path []AssetFolderDto) *AssetFoldersDto {
	this := AssetFoldersDto{}
	this.Links = links
	this.Items = items
	this.Path = path
	return &this
}

// NewAssetFoldersDtoWithDefaults instantiates a new AssetFoldersDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetFoldersDtoWithDefaults() *AssetFoldersDto {
	this := AssetFoldersDto{}
	return &this
}

// GetLinks returns the Links field value
func (o *AssetFoldersDto) GetLinks() map[string]ResourceLink {
	if o == nil {
		var ret map[string]ResourceLink
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AssetFoldersDto) GetLinksOk() (*map[string]ResourceLink, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AssetFoldersDto) SetLinks(v map[string]ResourceLink) {
	o.Links = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AssetFoldersDto) GetTotal() int64 {
	if o == nil || isNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetFoldersDto) GetTotalOk() (*int64, bool) {
	if o == nil || isNil(o.Total) {
    return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AssetFoldersDto) HasTotal() bool {
	if o != nil && !isNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *AssetFoldersDto) SetTotal(v int64) {
	o.Total = &v
}

// GetItems returns the Items field value
func (o *AssetFoldersDto) GetItems() []AssetFolderDto {
	if o == nil {
		var ret []AssetFolderDto
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AssetFoldersDto) GetItemsOk() ([]AssetFolderDto, bool) {
	if o == nil {
    return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AssetFoldersDto) SetItems(v []AssetFolderDto) {
	o.Items = v
}

// GetPath returns the Path field value
func (o *AssetFoldersDto) GetPath() []AssetFolderDto {
	if o == nil {
		var ret []AssetFolderDto
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *AssetFoldersDto) GetPathOk() ([]AssetFolderDto, bool) {
	if o == nil {
    return nil, false
	}
	return o.Path, true
}

// SetPath sets field value
func (o *AssetFoldersDto) SetPath(v []AssetFolderDto) {
	o.Path = v
}

func (o AssetFoldersDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["_links"] = o.Links
	}
	if !isNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if true {
		toSerialize["path"] = o.Path
	}
	return json.Marshal(toSerialize)
}

type NullableAssetFoldersDto struct {
	value *AssetFoldersDto
	isSet bool
}

func (v NullableAssetFoldersDto) Get() *AssetFoldersDto {
	return v.value
}

func (v *NullableAssetFoldersDto) Set(val *AssetFoldersDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetFoldersDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetFoldersDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetFoldersDto(val *AssetFoldersDto) *NullableAssetFoldersDto {
	return &NullableAssetFoldersDto{value: val, isSet: true}
}

func (v NullableAssetFoldersDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetFoldersDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


