/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 7.0.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// ImageFormat the model 'ImageFormat'
type ImageFormat string

// List of ImageFormat
const (
	AVIF ImageFormat = "AVIF"
	BMP  ImageFormat = "BMP"
	GIF  ImageFormat = "GIF"
	JPEG ImageFormat = "JPEG"
	PNG  ImageFormat = "PNG"
	TGA  ImageFormat = "TGA"
	TIFF ImageFormat = "TIFF"
	WEBP ImageFormat = "WEBP"
)
