/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// UpdateSettingDto struct for UpdateSettingDto
type UpdateSettingDto struct {
	// The value for the setting.
	Value IJsonValue `json:"value,omitempty"`
}
