/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// WorkflowTransitionDto struct for WorkflowTransitionDto
type WorkflowTransitionDto struct {
	// The optional expression.
	Expression *string `json:"expression,omitempty"`
	// The optional restricted role.
	Roles *[]string `json:"roles,omitempty"`
}
