/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// SchemasDto struct for SchemasDto
type SchemasDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The schemas.
	Items []SchemaDto `json:"items,omitempty"`
}
