/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient
// AssetType the model 'AssetType'
type AssetType string

// List of AssetType
const (
	UNKNOWN AssetType = "Unknown"
	IMAGE AssetType = "Image"
	AUDIO AssetType = "Audio"
	VIDEO AssetType = "Video"
)
