/*
Squidex API

Testing TranslationsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_openapi_TranslationsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test TranslationsApiService TranslationsPostTranslation", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var app string

        resp, httpRes, err := apiClient.TranslationsApi.TranslationsPostTranslation(context.Background(), app).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
