/*
Squidex API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 7.0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package squidexclient

import (
	"encoding/json"
)

// ElasticSearchRuleActionDtoAllOf struct for ElasticSearchRuleActionDtoAllOf
type ElasticSearchRuleActionDtoAllOf struct {
	// The url to the elastic search instance or cluster.
	Host string `json:"host"`
	// The name of the index.
	IndexName string `json:"indexName"`
	// The optional username.
	Username NullableString `json:"username,omitempty"`
	// The optional password.
	Password NullableString `json:"password,omitempty"`
	// The optional custom document.
	Document NullableString `json:"document,omitempty"`
	// The condition when to delete the document.
	Delete NullableString `json:"delete,omitempty"`
}

// NewElasticSearchRuleActionDtoAllOf instantiates a new ElasticSearchRuleActionDtoAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElasticSearchRuleActionDtoAllOf(host string, indexName string) *ElasticSearchRuleActionDtoAllOf {
	this := ElasticSearchRuleActionDtoAllOf{}
	this.Host = host
	this.IndexName = indexName
	return &this
}

// NewElasticSearchRuleActionDtoAllOfWithDefaults instantiates a new ElasticSearchRuleActionDtoAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElasticSearchRuleActionDtoAllOfWithDefaults() *ElasticSearchRuleActionDtoAllOf {
	this := ElasticSearchRuleActionDtoAllOf{}
	return &this
}

// GetHost returns the Host field value
func (o *ElasticSearchRuleActionDtoAllOf) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *ElasticSearchRuleActionDtoAllOf) GetHostOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *ElasticSearchRuleActionDtoAllOf) SetHost(v string) {
	o.Host = v
}

// GetIndexName returns the IndexName field value
func (o *ElasticSearchRuleActionDtoAllOf) GetIndexName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndexName
}

// GetIndexNameOk returns a tuple with the IndexName field value
// and a boolean to check if the value has been set.
func (o *ElasticSearchRuleActionDtoAllOf) GetIndexNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.IndexName, true
}

// SetIndexName sets field value
func (o *ElasticSearchRuleActionDtoAllOf) SetIndexName(v string) {
	o.IndexName = v
}

// GetUsername returns the Username field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ElasticSearchRuleActionDtoAllOf) GetUsername() string {
	if o == nil || isNil(o.Username.Get()) {
		var ret string
		return ret
	}
	return *o.Username.Get()
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ElasticSearchRuleActionDtoAllOf) GetUsernameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Username.Get(), o.Username.IsSet()
}

// HasUsername returns a boolean if a field has been set.
func (o *ElasticSearchRuleActionDtoAllOf) HasUsername() bool {
	if o != nil && o.Username.IsSet() {
		return true
	}

	return false
}

// SetUsername gets a reference to the given NullableString and assigns it to the Username field.
func (o *ElasticSearchRuleActionDtoAllOf) SetUsername(v string) {
	o.Username.Set(&v)
}
// SetUsernameNil sets the value for Username to be an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) SetUsernameNil() {
	o.Username.Set(nil)
}

// UnsetUsername ensures that no value is present for Username, not even an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) UnsetUsername() {
	o.Username.Unset()
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ElasticSearchRuleActionDtoAllOf) GetPassword() string {
	if o == nil || isNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ElasticSearchRuleActionDtoAllOf) GetPasswordOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *ElasticSearchRuleActionDtoAllOf) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *ElasticSearchRuleActionDtoAllOf) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) UnsetPassword() {
	o.Password.Unset()
}

// GetDocument returns the Document field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ElasticSearchRuleActionDtoAllOf) GetDocument() string {
	if o == nil || isNil(o.Document.Get()) {
		var ret string
		return ret
	}
	return *o.Document.Get()
}

// GetDocumentOk returns a tuple with the Document field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ElasticSearchRuleActionDtoAllOf) GetDocumentOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Document.Get(), o.Document.IsSet()
}

// HasDocument returns a boolean if a field has been set.
func (o *ElasticSearchRuleActionDtoAllOf) HasDocument() bool {
	if o != nil && o.Document.IsSet() {
		return true
	}

	return false
}

// SetDocument gets a reference to the given NullableString and assigns it to the Document field.
func (o *ElasticSearchRuleActionDtoAllOf) SetDocument(v string) {
	o.Document.Set(&v)
}
// SetDocumentNil sets the value for Document to be an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) SetDocumentNil() {
	o.Document.Set(nil)
}

// UnsetDocument ensures that no value is present for Document, not even an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) UnsetDocument() {
	o.Document.Unset()
}

// GetDelete returns the Delete field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ElasticSearchRuleActionDtoAllOf) GetDelete() string {
	if o == nil || isNil(o.Delete.Get()) {
		var ret string
		return ret
	}
	return *o.Delete.Get()
}

// GetDeleteOk returns a tuple with the Delete field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ElasticSearchRuleActionDtoAllOf) GetDeleteOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Delete.Get(), o.Delete.IsSet()
}

// HasDelete returns a boolean if a field has been set.
func (o *ElasticSearchRuleActionDtoAllOf) HasDelete() bool {
	if o != nil && o.Delete.IsSet() {
		return true
	}

	return false
}

// SetDelete gets a reference to the given NullableString and assigns it to the Delete field.
func (o *ElasticSearchRuleActionDtoAllOf) SetDelete(v string) {
	o.Delete.Set(&v)
}
// SetDeleteNil sets the value for Delete to be an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) SetDeleteNil() {
	o.Delete.Set(nil)
}

// UnsetDelete ensures that no value is present for Delete, not even an explicit nil
func (o *ElasticSearchRuleActionDtoAllOf) UnsetDelete() {
	o.Delete.Unset()
}

func (o ElasticSearchRuleActionDtoAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["host"] = o.Host
	}
	if true {
		toSerialize["indexName"] = o.IndexName
	}
	if o.Username.IsSet() {
		toSerialize["username"] = o.Username.Get()
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.Document.IsSet() {
		toSerialize["document"] = o.Document.Get()
	}
	if o.Delete.IsSet() {
		toSerialize["delete"] = o.Delete.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableElasticSearchRuleActionDtoAllOf struct {
	value *ElasticSearchRuleActionDtoAllOf
	isSet bool
}

func (v NullableElasticSearchRuleActionDtoAllOf) Get() *ElasticSearchRuleActionDtoAllOf {
	return v.value
}

func (v *NullableElasticSearchRuleActionDtoAllOf) Set(val *ElasticSearchRuleActionDtoAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableElasticSearchRuleActionDtoAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableElasticSearchRuleActionDtoAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElasticSearchRuleActionDtoAllOf(val *ElasticSearchRuleActionDtoAllOf) *NullableElasticSearchRuleActionDtoAllOf {
	return &NullableElasticSearchRuleActionDtoAllOf{value: val, isSet: true}
}

func (v NullableElasticSearchRuleActionDtoAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElasticSearchRuleActionDtoAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


