/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 5.3.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidexclient

// PatternsDtoAllOf struct for PatternsDtoAllOf
type PatternsDtoAllOf struct {
	// The patterns.
	Items []PatternDto `json:"items"`
}
