openapi: 3.0.0
info:
  title: Squidex API
  version: 4.1.3.0
  x-logo:
    url: https://squidex-embracecloudte.features.embracecloud.io/images/logo-white.png
    backgroundColor: '#3f83df'
servers:
- url: https://squidex-embracecloudte.features.embracecloud.io/api
security:
- squidex-oauth-auth: []
paths:
  /:
    get:
      operationId: Users_GetUserResources
      security:
      - squidex-oauth-auth: []
      summary: Get the user resources.
      tags:
      - Users
  /users:
    get:
      description: Search the user by query that contains the email address or the
        part of the email address.
      operationId: Users_GetUsers
      security:
      - squidex-oauth-auth: []
      summary: Get users by query.
      tags:
      - Users
  /users/{id}:
    get:
      operationId: Users_GetUser
      security:
      - squidex-oauth-auth: []
      summary: Get user by id.
      tags:
      - Users
  /users/{id}/picture:
    get:
      operationId: Users_GetUserPicture
      summary: Get user picture by id.
      tags:
      - Users
  /apps/{app}/translations:
    post:
      operationId: Translations_GetLanguages
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Translate a text.
      tags:
      - Translations
  /apps/{app}/usages/log:
    get:
      operationId: Usages_GetLog
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get api calls as log file.
      tags:
      - Statistics
  /apps/{app}/usages/calls/month:
    get:
      operationId: Usages_GetMonthlyCalls
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get api calls for this month.
      tags:
      - Statistics
  /apps/{app}/usages/calls/{fromDate}/{toDate}:
    get:
      operationId: Usages_GetUsages
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get api calls in date range.
      tags:
      - Statistics
  /apps/{app}/usages/storage/today:
    get:
      operationId: Usages_GetCurrentStorageSize
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get total asset size.
      tags:
      - Statistics
  /apps/{app}/usages/storage/{fromDate}/{toDate}:
    get:
      operationId: Usages_GetStorageSizes
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get asset usage by date.
      tags:
      - Statistics
  /apps/{app}/schemas/{name}/fields:
    post:
      operationId: SchemaFields_PostField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Add a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested:
    post:
      operationId: SchemaFields_PostNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Add a nested schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/ui:
    put:
      operationId: SchemaFields_PutSchemaUIFields
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Configure UI fields.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/ordering:
    put:
      operationId: SchemaFields_PutSchemaFieldOrdering
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Reorders the fields.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/ordering:
    put:
      operationId: SchemaFields_PutNestedFieldOrdering
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Reorders the nested fields.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{id}:
    delete:
      operationId: SchemaFields_DeleteField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Delete a schema field.
      tags:
      - Schemas
    put:
      operationId: SchemaFields_PutField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Update a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/{id}:
    delete:
      operationId: SchemaFields_DeleteNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Delete a nested schema field.
      tags:
      - Schemas
    put:
      operationId: SchemaFields_PutNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Update a nested schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{id}/lock:
    put:
      description: A locked field cannot be updated or deleted.
      operationId: SchemaFields_LockField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Lock a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/{id}/lock:
    put:
      description: A locked field cannot be edited or deleted.
      operationId: SchemaFields_LockNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Lock a nested schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{id}/hide:
    put:
      description: A hidden field is not part of the API response, but can still be
        edited in the portal.
      operationId: SchemaFields_HideField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Hide a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/{id}/hide:
    put:
      description: A hidden field is not part of the API response, but can still be
        edited in the portal.
      operationId: SchemaFields_HideNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Hide a nested schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{id}/show:
    put:
      description: A hidden field is not part of the API response, but can still be
        edited in the portal.
      operationId: SchemaFields_ShowField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Show a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/{id}/show:
    put:
      description: A hidden field is not part of the API response, but can still be
        edited in the portal.
      operationId: SchemaFields_ShowNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Show a nested schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{id}/enable:
    put:
      description: A disabled field cannot not be edited in the squidex portal anymore,
        but will be part of the API response.
      operationId: SchemaFields_EnableField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Enable a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/{id}/enable:
    put:
      description: A disabled field cannot not be edited in the squidex portal anymore,
        but will be part of the API response.
      operationId: SchemaFields_EnableNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Enable a nested schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{id}/disable:
    put:
      description: A disabled field cannot not be edited in the squidex portal anymore,
        but will be part of the API response.
      operationId: SchemaFields_DisableField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Disable a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/fields/{parentId}/nested/{id}/disable:
    put:
      description: A disabled field cannot not be edited in the squidex portal anymore,
        but will be part of the API response.
      operationId: SchemaFields_DisableNestedField
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Disable nested a schema field.
      tags:
      - Schemas
  /apps/{app}/schemas:
    get:
      operationId: Schemas_GetSchemas
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get schemas.
      tags:
      - Schemas
    post:
      operationId: Schemas_PostSchema
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.create
      summary: Create a new schema.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}:
    delete:
      operationId: Schemas_DeleteSchema
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.delete
      summary: Delete a schema.
      tags:
      - Schemas
    get:
      operationId: Schemas_GetSchema
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get a schema by name.
      tags:
      - Schemas
    put:
      operationId: Schemas_PutSchema
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Update a schema.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/sync:
    put:
      operationId: Schemas_PutSchemaSync
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Synchronize a schema.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/category:
    put:
      operationId: Schemas_PutCategory
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Update a schema category.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/preview-urls:
    put:
      operationId: Schemas_PutPreviewUrls
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.update
      summary: Update the preview urls.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/scripts:
    put:
      operationId: Schemas_PutScripts
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.scripts
      summary: Update the scripts.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/publish:
    put:
      operationId: Schemas_PublishSchema
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.publish
      summary: Publish a schema.
      tags:
      - Schemas
  /apps/{app}/schemas/{name}/unpublish:
    put:
      operationId: Schemas_UnpublishSchema
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.schemas.{name}.publish
      summary: Unpublish a schema.
      tags:
      - Schemas
  /rules/actions:
    get:
      operationId: Rules_GetActions
      security:
      - squidex-oauth-auth: []
      summary: Get the supported rule actions.
      tags:
      - Rules
  /apps/{app}/rules:
    get:
      operationId: Rules_GetRules
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.read
      summary: Get rules.
      tags:
      - Rules
    post:
      operationId: Rules_PostRule
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.create
      summary: Create a new rule.
      tags:
      - Rules
  /apps/{app}/rules/{id}:
    delete:
      operationId: Rules_DeleteRule
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.delete
      summary: Delete a rule.
      tags:
      - Rules
    put:
      description: All events for the specified schemas will be sent to the url. The
        timeout is 2 seconds.
      operationId: Rules_PutRule
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.update
      summary: Update a rule.
      tags:
      - Rules
  /apps/{app}/rules/{id}/enable:
    put:
      operationId: Rules_EnableRule
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.disable
      summary: Enable a rule.
      tags:
      - Rules
  /apps/{app}/rules/{id}/disable:
    put:
      operationId: Rules_DisableRule
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.disable
      summary: Disable a rule.
      tags:
      - Rules
  /apps/{app}/rules/{id}/trigger:
    put:
      operationId: Rules_TriggerRule
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.events
      summary: Trigger a rule.
      tags:
      - Rules
  /apps/{app}/rules/events:
    get:
      operationId: Rules_GetEvents
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.read
      summary: Get rule events.
      tags:
      - Rules
  /apps/{app}/rules/events/{id}:
    delete:
      operationId: Rules_DeleteEvent
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.events
      summary: Cancels the event and retries.
      tags:
      - Rules
    put:
      operationId: Rules_PutEvent
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.rules.events
      summary: Retry the event immediately.
      tags:
      - Rules
  /apps/{app}/plans:
    get:
      operationId: AppPlans_GetPlans
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.plans.read
      summary: Get app plan information.
      tags:
      - Plans
  /apps/{app}/plan:
    put:
      operationId: AppPlans_PutPlan
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.plans.change
      summary: Change the app plan.
      tags:
      - Plans
  /info:
    get:
      operationId: Ping_GetInfo
      summary: Get general info status of the API.
      tags:
      - Ping
  /ping:
    get:
      description: Can be used to test, if the Squidex API is alive and responding.
      operationId: Ping_GetPing
      summary: Get ping status of the API.
      tags:
      - Ping
  /ping/{app}:
    get:
      description: Can be used to test, if the Squidex API is alive and responding.
      operationId: Ping_GetAppPing
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get ping status.
      tags:
      - Ping
  /news/features:
    get:
      operationId: News_GetLanguages
      security:
      - squidex-oauth-auth: []
      summary: Get features since version.
      tags:
      - News
  /languages:
    get:
      description: Provide a list of supported language codes, following the ISO2Code
        standard.
      operationId: Languages_GetLanguages
      security:
      - squidex-oauth-auth: []
      summary: Get supported languages.
      tags:
      - Languages
  /apps/{app}/history:
    get:
      operationId: History_GetHistory
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get the events from the history.
      tags:
      - History
  /apps/{app}/comments/{commentsId}:
    get:
      description: When passing in a version you can retrieve all updates since then.
      operationId: Comments_GetComments
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get all comments.
      tags:
      - Comments
    post:
      operationId: Comments_PostComment
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Create a new comment.
      tags:
      - Comments
  /apps/{app}/comments/{commentsId}/{commentId}:
    delete:
      operationId: Comments_DeleteComment
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Deletes the comment.
      tags:
      - Comments
    put:
      operationId: Comments_PutComment
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Updates the comment.
      tags:
      - Comments
  /users/{userId}/notifications:
    get:
      description: When passing in a version you can retrieve all updates since then.
      operationId: UserNotifications_GetNotifications
      security:
      - squidex-oauth-auth: []
      summary: Get all notifications.
      tags:
      - Notifications
  /users/{userId}/notifications/{commentId}:
    delete:
      operationId: UserNotifications_DeleteComment
      security:
      - squidex-oauth-auth: []
      summary: Deletes the notification.
      tags:
      - Notifications
  /apps/{app}/backups/{id}:
    delete:
      operationId: Backups_DeleteBackup
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.backups.delete
      summary: Delete a backup.
      tags:
      - Backups
    get:
      operationId: BackupContent_GetBackupContent
      summary: Get the backup content.
      tags:
      - Backups
  /apps/{app}/backups:
    get:
      operationId: Backups_GetBackups
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.backups.read
      summary: Get all backup jobs.
      tags:
      - Backups
    post:
      operationId: Backups_PostBackup
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.backups.create
      summary: Start a new backup.
      tags:
      - Backups
  /apps/restore:
    get:
      operationId: Restore_GetRestoreJob
      security:
      - squidex-oauth-auth:
        - squidex.admin.restore
      summary: Get current restore status.
      tags:
      - Backups
    post:
      operationId: Restore_PostRestoreJob
      security:
      - squidex-oauth-auth:
        - squidex.admin.restore
      summary: Restore a backup.
      tags:
      - Backups
  /assets/{app}/{idOrSlug}/{more}:
    get:
      operationId: AssetContent_GetAssetContentBySlug
      security:
      - squidex-oauth-auth: []
      summary: Get the asset content.
      tags:
      - Assets
  /apps/{app}/assets/folders:
    get:
      description: Get all asset folders for the app.
      operationId: AssetFolders_GetAssetFolders
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.read
      summary: Get asset folders.
      tags:
      - Assets
    post:
      operationId: AssetFolders_PostAssetFolder
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.update
      summary: Upload a new asset.
      tags:
      - Assets
  /apps/{app}/assets/folders/{id}:
    delete:
      operationId: AssetFolders_DeleteAssetFolder
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.update
      summary: Delete an asset folder.
      tags:
      - Assets
    put:
      operationId: AssetFolders_PutAssetFolder
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.update
      summary: Updates the asset folder.
      tags:
      - Assets
  /apps/{app}/assets/folders/{id}/parent:
    put:
      operationId: AssetFolders_PutAssetFolderParent
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.update
      summary: Moves the asset folder.
      tags:
      - Assets
  /apps/{app}/assets/tags:
    get:
      description: Get all tags for assets.
      operationId: Assets_GetTags
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.read
      summary: Get assets tags.
      tags:
      - Assets
  /apps/{app}/assets/{id}:
    delete:
      operationId: Assets_DeleteAsset
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.delete
      summary: Delete an asset.
      tags:
      - Assets
    get:
      operationId: Assets_GetAsset
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.read
      summary: Get an asset by id.
      tags:
      - Assets
    put:
      operationId: Assets_PutAsset
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.update
      summary: Updates the asset.
      tags:
      - Assets
  /apps/{app}/assets/{id}/parent:
    put:
      operationId: Assets_PutAssetParent
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.assets.update
      summary: Moves the asset.
      tags:
      - Assets
  /apps/{app}/clients:
    get:
      description: Gets all configured clients for the app with the specified name.
      operationId: AppClients_GetClients
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.clients.read
      summary: Get app clients.
      tags:
      - Apps
    post:
      description: |-
        Create a new client for the app with the specified name.
        The client secret is auto generated on the server and returned. The client does not exire, the access token is valid for 30 days.
      operationId: AppClients_PostClient
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.clients.create
      summary: Create a new app client.
      tags:
      - Apps
  /apps/{app}/clients/{id}:
    delete:
      description: The application that uses this client credentials cannot access
        the API after it has been revoked.
      operationId: AppClients_DeleteClient
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.clients.delete
      summary: Revoke an app client.
      tags:
      - Apps
    put:
      description: Only the display name can be changed, create a new client if necessary.
      operationId: AppClients_PutClient
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.clients.update
      summary: Updates an app client.
      tags:
      - Apps
  /apps/{app}/contributors:
    get:
      operationId: AppContributors_GetContributors
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get app contributors.
      tags:
      - Apps
    post:
      operationId: AppContributors_PostContributor
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.contributors.assign
      summary: Assign contributor to app.
      tags:
      - Apps
  /apps/{app}/contributors/{id}:
    delete:
      operationId: AppContributors_DeleteContributor
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.contributors.revoke
      summary: Remove contributor from app.
      tags:
      - Apps
  /apps/{app}/languages:
    get:
      operationId: AppLanguages_GetLanguages
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get app languages.
      tags:
      - Apps
    post:
      operationId: AppLanguages_PostLanguage
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.languages.create
      summary: Attaches an app language.
      tags:
      - Apps
  /apps/{app}/languages/{language}:
    delete:
      operationId: AppLanguages_DeleteLanguage
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.languages.delete
      summary: Deletes an app language.
      tags:
      - Apps
    put:
      operationId: AppLanguages_PutLanguage
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.languages.update
      summary: Updates an app language.
      tags:
      - Apps
  /apps/{app}/patterns:
    get:
      description: Gets all configured regex patterns for the app with the specified
        name.
      operationId: AppPatterns_GetPatterns
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.common
      summary: Get app patterns.
      tags:
      - Apps
    post:
      operationId: AppPatterns_PostPattern
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.patterns.create
      summary: Create a new app pattern.
      tags:
      - Apps
  /apps/{app}/patterns/{id}:
    delete:
      description: Schemas using this pattern will still function using the same Regular
        Expression.
      operationId: AppPatterns_DeletePattern
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.patterns.delete
      summary: Delete an existing app pattern.
      tags:
      - Apps
    put:
      operationId: AppPatterns_PutPattern
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.patterns.update
      summary: Update an existing app pattern.
      tags:
      - Apps
  /apps/{app}/roles:
    get:
      operationId: AppRoles_GetRoles
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.roles.read
      summary: Get app roles.
      tags:
      - Apps
    post:
      operationId: AppRoles_PostRole
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.roles.create
      summary: Add role to app.
      tags:
      - Apps
  /apps/{app}/roles/permissions:
    get:
      operationId: AppRoles_GetPermissions
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.roles.read
      summary: Get app permissions.
      tags:
      - Apps
  /apps/{app}/roles/{name}:
    delete:
      operationId: AppRoles_DeleteRole
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.roles.delete
      summary: Remove role from app.
      tags:
      - Apps
    put:
      operationId: AppRoles_PutRole
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.roles.update
      summary: Update an existing app role.
      tags:
      - Apps
  /apps:
    get:
      description: |-
        You can only retrieve the list of apps when you are authenticated as a user (OpenID implicit flow).
        You will retrieve all apps, where you are assigned as a contributor.
      operationId: Apps_GetApps
      security:
      - squidex-oauth-auth: []
      summary: Get your apps.
      tags:
      - Apps
    post:
      description: |-
        You can only create an app when you are authenticated as a user (OpenID implicit flow).
        You will be assigned as owner of the new app automatically.
      operationId: Apps_PostApp
      security:
      - squidex-oauth-auth: []
      summary: Create a new app.
      tags:
      - Apps
  /apps/{app}:
    delete:
      operationId: Apps_DeleteApp
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.delete
      summary: Archive the app.
      tags:
      - Apps
    get:
      operationId: Apps_GetApp
      security:
      - squidex-oauth-auth: []
      summary: Get an app by name.
      tags:
      - Apps
    put:
      operationId: Apps_UpdateApp
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.general
      summary: Update the app.
      tags:
      - Apps
  /apps/{app}/workflows:
    get:
      operationId: AppWorkflows_GetWorkflows
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.workflows.read
      summary: Get app workflow.
      tags:
      - Apps
    post:
      operationId: AppWorkflows_PostWorkflow
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.workflows.update
      summary: Create a workflow.
      tags:
      - Apps
  /apps/{app}/workflows/{id}:
    delete:
      operationId: AppWorkflows_DeleteWorkflow
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.workflows.update
      summary: Delete a workflow.
      tags:
      - Apps
    put:
      operationId: AppWorkflows_PutWorkflow
      security:
      - squidex-oauth-auth:
        - squidex.apps.{app}.workflows.update
      summary: Update a workflow.
      tags:
      - Apps
components:
  securitySchemes:
    squidex-oauth-auth:
      description: "Squidex uses oauth2 client authentication. Read more about it\
        \ at: https://oauth.net/2/ and https://tools.ietf.org/html/rfc6750.\n\nTo\
        \ retrieve an access token, the client id must make a request to the token\
        \ url. For example:\n\n    $ curl\n        -X POST 'https://squidex-embracecloudte.features.embracecloud.io/identity-server/connect/token'\
        \ \n        -H 'Content-Type: application/x-www-form-urlencoded' \n      \
        \  -d 'grant_type=client_credentials&\n            client_id=[APP_NAME]:[CLIENT_ID]&\n\
        \            client_secret=[CLIENT_SECRET]&\n\t\t\tscope=squidex-api'\n\n\
        `[APP_NAME]` is the name of your app. You have to create a client to generate\
        \ an access token.\n\nYou must send this token in the `Authorization` header\
        \ when making requests to the API:\n\n     Authorization: Bearer <token>"
      flows:
        clientCredentials:
          scopes:
            squidex-api: Read and write access to the API
          tokenUrl: https://squidex-embracecloudte.features.embracecloud.io/identity-server/connect/token
      type: oauth2
x-generator: NSwag v13.2.2.0 (NJsonSchema v10.1.5.0 (Newtonsoft.Json v12.0.0.0))
