/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// GeolocationFieldEditor the model 'GeolocationFieldEditor'
type GeolocationFieldEditor string

// List of GeolocationFieldEditor
const (
	MAP GeolocationFieldEditor = "Map"
)
