/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// EventConsumersDtoAllOf struct for EventConsumersDtoAllOf
type EventConsumersDtoAllOf struct {
	// The event consumers.
	Items []EventConsumerDto `json:"items,omitempty"`
}
