/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// RuleActionPropertyEditor the model 'RuleActionPropertyEditor'
type RuleActionPropertyEditor string

// List of RuleActionPropertyEditor
const (
	CHECKBOX RuleActionPropertyEditor = "Checkbox"
	EMAIL RuleActionPropertyEditor = "Email"
	NUMBER RuleActionPropertyEditor = "Number"
	PASSWORD RuleActionPropertyEditor = "Password"
	TEXT RuleActionPropertyEditor = "Text"
	TEXT_AREA RuleActionPropertyEditor = "TextArea"
	URL RuleActionPropertyEditor = "Url"
)
