/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// KeyValuePairOfStringAndContentFieldData struct for KeyValuePairOfStringAndContentFieldData
type KeyValuePairOfStringAndContentFieldData struct {
	Key string `json:"key,omitempty"`
	Value map[string]IJsonValue `json:"value,omitempty"`
}
