/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// UpsertCommentDto struct for UpsertCommentDto
type UpsertCommentDto struct {
	// The comment text.
	Text string `json:"text"`
	// The url where the comment is created.
	Url *string `json:"url,omitempty"`
}
