/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// UpdateSettingDto struct for UpdateSettingDto
type UpdateSettingDto struct {
	// The value for the setting.
	Value OneOfIJsonValue `json:"value,omitempty"`
}
