/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// AlgoliaRuleActionDto struct for AlgoliaRuleActionDto
type AlgoliaRuleActionDto struct {
	ActionType string `json:"actionType"`
	// The application ID.
	AppId string `json:"appId"`
	// The API key to grant access to Squidex.
	ApiKey string `json:"apiKey"`
	// The name of the index.
	IndexName string `json:"indexName"`
	// The optional custom document.
	Document *string `json:"document,omitempty"`
}
