/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// UsageRuleTriggerDtoAllOf struct for UsageRuleTriggerDtoAllOf
type UsageRuleTriggerDtoAllOf struct {
	// The number of monthly api calls.
	Limit int32 `json:"limit,omitempty"`
	// The number of days to check or null for the current month.
	NumDays *int32 `json:"numDays,omitempty"`
}
