/*
 * Squidex API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 4.1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package squidex-client
// ClientDto struct for ClientDto
type ClientDto struct {
	// The links.
	Links map[string]ResourceLink `json:"_links"`
	// The client id.
	Id string `json:"id"`
	// The client secret.
	Secret string `json:"secret"`
	// The client name.
	Name string `json:"name"`
	// The role of the client.
	Role *string `json:"role,omitempty"`
}
